import { defineConfig } from 'vite'
import { resolve } from 'path'
import fs from 'fs'

// Auto-discover article pages (generated by build-articles.js)
function getArticleInputs() {
  const articlesDir = resolve(__dirname, 'articles')
  const inputs = {}

  if (!fs.existsSync(articlesDir)) return inputs

  // Articles listing page
  const listingPage = resolve(articlesDir, 'index.html')
  if (fs.existsSync(listingPage)) {
    inputs['articles'] = listingPage
  }

  // Individual article pages
  const entries = fs.readdirSync(articlesDir, { withFileTypes: true })
  for (const entry of entries) {
    if (entry.isDirectory()) {
      const indexPath = resolve(articlesDir, entry.name, 'index.html')
      if (fs.existsSync(indexPath)) {
        inputs[`article-${entry.name}`] = indexPath
      }
    }
  }

  return inputs
}

export default defineConfig({
  base: '/',
  publicDir: 'public',
  build: {
    outDir: 'dist',
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        about: resolve(__dirname, 'about/index.html'),
        models: resolve(__dirname, 'models/index.html'),
        ...getArticleInputs(),
      }
    }
  }
})
