import { defineConfig } from 'vite'
import { resolve } from 'path'
import fs from 'fs'

// Auto-discover article pages (generated by build-articles.js)
function getArticleInputs() {
  const inputs = {}
  const dirsToScan = [
    { path: resolve(__dirname, 'articles'), prefix: 'zh' },
    { path: resolve(__dirname, 'en/articles'), prefix: 'en' }
  ];

  for (const { path: dirPath, prefix } of dirsToScan) {
    if (!fs.existsSync(dirPath)) continue;

    // Articles listing page
    const listingPage = resolve(dirPath, 'index.html')
    if (fs.existsSync(listingPage)) {
      inputs[`articles-${prefix}`] = listingPage
    }

    // Individual article pages
    const entries = fs.readdirSync(dirPath, { withFileTypes: true })
    for (const entry of entries) {
      if (entry.isDirectory()) {
        const indexPath = resolve(dirPath, entry.name, 'index.html')
        if (fs.existsSync(indexPath)) {
          inputs[`article-${prefix}-${entry.name}`] = indexPath
        }
      }
    }
  }

  return inputs
}

export default defineConfig({
  base: '/',
  publicDir: 'public',
  build: {
    outDir: 'dist',
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        about: resolve(__dirname, 'about/index.html'),
        models: resolve(__dirname, 'models/index.html'),
        projects: resolve(__dirname, 'projects/index.html'),
        mainEn: resolve(__dirname, 'en/index.html'),
        aboutEn: resolve(__dirname, 'en/about/index.html'),
        modelsEn: resolve(__dirname, 'en/models/index.html'),
        projectsEn: resolve(__dirname, 'en/projects/index.html'),
        ...getArticleInputs(),
      }
    }
  }
})
